# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'OpenWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxCocoa'
  pod 'RxSwift', '~> 6.5.0'
  pod 'Alamofire', '~> 5.5'
  pod 'SnapKit'

  # Pods for OpenWeather

end
